# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'

arch: amd64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis


script:
  - tox


stages:
  - test
  - deploy_pypi



jobs:
  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: test
      arch: arm64
      python: 3.8

    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/git-toggle
        provider: pypi
        user: "DomDF"
        password:
          secure:
        distributions: "sdist bdist_wheel"
        skip_existing: true
